name: Android CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.6
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create the Keystore from Secrets to Sign the App
      env:
        ENCODED_KEYSTORE: ${{ secrets.SIGNING_KEY }}
        ENCODED_PROPS: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: |
        if [ "$ENCODED_PROPS" == "" ]; then
          exit
        fi
        echo $ENCODED_KEYSTORE | base64 -d > ${{ github.workspace }}/release.jks
        echo $ENCODED_PROPS | base64 -d > ${{ github.workspace }}/keystore.properties

    # Android NDK

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleOpenRelease

    - name: Upload Apk to Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ${{ github.workspace }}/app/build/outputs/apk/open/release/*.apk

    - name: Auto Release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: true
        tag_name: "Night"
        fail_on_unmatched_files: true
        files: |
          ${{ github.workspace }}/app/build/outputs/apk/open/release/*.apk
